### ISSUE TITLE
Setting custom git using gitExec does not pass git flow 

### ISSUE THREAD

**Issue by alexisaperez** [piuccio/git-promise#4]
Hello, I was working on getting git-control to work in El Capitan and saw you posted a fix to set a custom path for git. When running the new code normal git functions work as expected but when I issue a call for git flow I get  `'/path/to/git flow -d' is not a git command error 1`. If I run `'/path/to/git flow -d'` in terminal it works fine. Any ideas on why normal git functions work fine but git flow does not?

**Comment by piuccio** [comment]
As of #8 the was commands are executed changed significantly. I'm assuming this is not relevant anymore, but if it's still a problem feel free to reopen.
