### ISSUE TITLE
Failure when using cwd option locks up directory

### ISSUE THREAD

**Issue by ByronPhung** [piuccio/git-promise#5]
When writing unit tests for one of my own personal projects, I ran into a consistent and reproducible issue that a failing git-promise call using the cwd option locks up the directory until the process is finally terminated.

I've successfully tested a fix locally but will perform a few additional tests before creating a pull request.

Background/Reasoning for Fix:

Although I don't anticipate it to be a common problem, this can be an issue for tests or modules dependent on making directory changes, such as cloning or removing, for cwd directories. In my situation, I've written unit tests using Mocha that use the before() and after() hooks to clone and clean up the directory once the module testing is completed. However, due to the lock issue, my other unit tests that use the same repository in the process fail because they cannot properly clone/clean up the cwd directories.

**Comment by ByronPhung** [comment]
Applied fix and wrote a unit test for this issue locally, but I don't have permissions to push to a branch and create a pull request.

If possible, please advise me on how we can review the changes :).

**Comment by piuccio** [comment]
You can create a fork and push your branch there, then open a PR
